---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hajimari
  namespace: services
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    hajimari:
      title: Dashboard
      lightTheme: horizon
      darkTheme: horizon
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: false
      showAppStatus: true
      showAppUrls: false
      showAppInfo: true
      showBookmarkGroups: true
      showGlobalBookmarks: false
      defaultEnable: true
      defaultAppIcon: mdi:application
      defaultSearchProvider: Google
      namespaceSelector:
        matchNames:
          - media
          - home-automation
          # - playground
          - services
          - monitoring
          - rp
      customApps:
        - group: Homelab
          apps:
          - name: PVE
            url: "https://192.168.100.5:8006"
            icon: https://github.com/walkxcode/dashboard-icons/raw/main/svg/proxmox.svg
          - name: PBS
            url: "https://192.168.100.5:8007"
            icon: https://github.com/walkxcode/dashboard-icons/raw/main/svg/proxmox.svg
          - name: iDRAC
            url: "https://192.168.100.9"
            icon: https://github.com/walkxcode/dashboard-icons/raw/main/svg/idrac.svg
          - name: UniFi
            url: "https://192.168.100.20:8443/"
            icon: https://github.com/walkxcode/dashboard-icons/raw/main/svg/unifi.svg
          - name: NextDNS
            url: "https://nextdns.com"
            icon: https://github.com/walkxcode/dashboard-icons/raw/main/svg/nextdns.svg
          - name: Minio
            url: "https://minio.lan"
            # icon: simple-icons:minio
            icon: https://github.com/walkxcode/dashboard-icons/raw/main/svg/minio.svg
      globalBookmarks:
        - group: Dev
          bookmarks:
            - name: ChatGPT
              url: "https://chat.openai.com/"
            - name: vmlab
              url: "https://github.com/srliao/vmlab"
            - name: gcsim
              url: "https://github.com/genshinsim/gcsim"
            - name: CyberChef
              url: "https://gchq.github.io/CyberChef"
        - group: Cloud
          bookmarks:
            - name: Google Drive
              url: "https://drive.google.com"
            - name: Gmail
              url: "https://gmail.com"
            - name: Cloudflare
              url: "https://dash.cloudflare.com"
        - group: Downloads
          bookmarks:
            - name: qBittorent
              url: https://gimmeabreak.beryl.usbx.me/qbittorrent/
            - name: Transmission
              url: https://gimmeabreak.beryl.usbx.me/transmission/web/
            - name: ruTorrent
              url: https://gimmeabreak.beryl.usbx.me/rutorrent/
      searchProviders:
        - name: Google
          token: g
          icon: simple-icons:google
          searchUrl: https://www.google.com/search?q={query}
          url: https://www.google.com
        - name: DuckDuckGo
          token: d
          icon: simple-icons:duckduckgo
          searchUrl: https://duckduckgo.com/?q={query}
          url: https://duckduckgo.com
        - name: IMDB
          token: i
          icon: simple-icons:imdb
          searchUrl: https://www.imdb.com/find?q={query}
          url: https://www.imdb.com
        - name: Reddit
          token: r
          icon: simple-icons:reddit
          searchUrl: https://www.reddit.com/search?q={query}
          url: https://www.reddit.com
        - name: YouTube
          token: "y"
          icon: simple-icons:youtube
          searchUrl: https://www.youtube.com/results?search_query={query}
          url: https://www.youtube.com
        - name: Spotify
          token: s
          icon: simple-icons:spotify
          searchUrl: hhttps://open.spotify.com/search/{query}
          url: https://open.spotify.com
        - name: WolframAlpha
          token: w
          icon: simple-icons:wolfram
          searchUrl: https://www.wolframalpha.com/input?i={query}
          url: https://www.wolframalpha.com
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: "hajimari.winterspring.ca"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.winterspring.ca"
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 64M
