---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app metube
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      metube:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/alexta69/metube
              tag: "2024-03-11 "
            env:
              TZ: America/Toronto
              DOWNLOAD_DIR: "/storage/media/downloads"
              TEMP_DIR: "/storage/media/downloads"
              STATE_DIR: "/config"
              YTDL_OPTIONS: '{"http_headers":{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"}}'
        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            runAsNonRoot: true
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8081
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/appName: "MeTube"
          hajimari.io/icon: https://github.com/walkxcode/dashboard-icons/raw/main/svg/metube.svg
        hosts:
          - host: &host '{{ .Release.Name }}.winterspring.ca'
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config
      media:
        type: nfs
        server: 192.168.100.5
        path: "/storage/media/downloads"
        globalMounts:
          - path: "/storage/media/downloads"
