---
apiVersion: v1
kind: Service
# load balancer service
metadata:
  name: postgres-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pg.winterspring.ca
    io.cilium/lb-ipam-ips: 192.168.100.40
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    role: primary
