---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pgadmin
  namespace: flux-system
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/database/pgadmin/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: external-secrets-stores
    - name: volsync
    - name: democratic-csi-local-path
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 2Gi
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
