---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app volsync-test
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      volsync-test:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/srliao/volsync-test-develop
              tag: rolling@sha256:d8ba3e78be3783ae7a0251ef90b90919b2f0d4c202b5d86d2aa27a45099b302b
              pullPolicy: Always
            env:
              PORT: &port 7777
              TZ: America/Toronto
              DATA_DIR: /data
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 64Mi
    service:
      app:
        controller: volsync-test
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        nameOverride: *app
        className: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host '{{ .Release.Name }}.${SECRET_DOMAIN}'
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: volsync-test-migrate

