---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-ngx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-ngx-secret
    template:
      engineVersion: v2
      data:
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBHOST : &dbHost postgres-rw.database.svc.cluster.local
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: &dbName paperless
        PAPERLESS_DBUSER: &dbUser "{{ .PAPERLESS_NGX_POSTGRES_USER }}"
        PAPERLESS_DBPASS: &dbPass "{{ .PAPERLESS_NGX_POSTGRES_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: paperless-ngx
    - extract:
        key: cloudnative-pg
