---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      paperless-ngx:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: paperless-ngx-secret

        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.6.3@sha256:101f3cbfd1e15f9dc3303f2eeb64dd4a9489f121accb31612c9ff8be93ba8094
            env:
              COMPOSE_PROJECT_NAME: paperless-ngx
              PAPERLESS_TIME_ZONE: America/Toronto
              # PAPERLESS_REDIS: redis://paperless-ngx-redis-master:6379
              PAPERLESS_REDIS: redis://redis-node-0.redis-headless.database.svc.cluster.local:26379
              # need this to place nice with nfs
              USERMAP_UID: 105000
              USERMAP_GID: 105000
              PAPERLESS_CONSUMPTION_DIR: /documents/scans
              PAPERLESS_DATA_DIR: /paperless/data
              PAPERLESS_MEDIA_ROOT: /pp/media
              PAPERLESS_TRASH_DIR: /pp/trash
              # to change these settings accordignly
              PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{title}"
              PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: true
              PAPERLESS_CONSUMER_POLLING: 60
              PAPERLESS_CONSUMER_DELETE_DUPLICATES: true
              PAPERLESS_CONSUMER_RECURSIVE: true
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 8000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 20m
              limits:
                memory: 1Gi

        # pod:
        #   securityContext:
        #     runAsUser: 105000
        #     runAsGroup: 105000
        #     runAsNonRoot: true
        #     fsGroup: 105000
        #     fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: paperless-ngx
        ports:
          http:
            port: *port

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: simple-icons:paperlessngx
        hosts:
          - host: &host "{{ .Release.Name }}.winterspring.ca"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: paperless-ngx-data
        globalMounts:
        - path: /paperless/data
      # media:
      #   type: nfs
      #   server: 192.168.100.5
      #   path: storage/documents/paperless/media
      #   globalMounts:
      #     - path: /paperless/media
      consume:
        type: nfs
        server: 192.168.100.5
        path: /storage/documents
        globalMounts:
          - path: /documents
      trash:
        type: nfs
        server: 192.168.100.5
        path: /storage/documents/paperless
        globalMounts:
          - path: /pp

