---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: paperless-ngx-bootstrap
