---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-redis
spec:
  storageClassName: local-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
