---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mealie-secret
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: &dbUser "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .POSTGRES_PASS }}"
        POSTGRES_SERVER: &dbHost postgres-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DB: &dbName mealie_main
        DB_ENGINE: "postgres"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: mealie
