---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: "OnRootMismatch"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.4.0
            envFrom: &envFrom
              - secretRef:
                  name: mealie-secret
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v2.8.0
            env:
              TZ: America/Toronto
              BASE_URL: https://mealie.winterspring.ca
              ALLOW_SIGNUP: "false"
              AUTO_BACKUP_ENABLED: "true"
              API_DOCS: "false"
              WORKERS_PER_CORE: "1"
              MAX_WORKERS: "1"
              WEB_CONCURRENCY: "1"
            envFrom: *envFrom
    service:
      app:
        controller: mealie
        ports:
          http:
            port: &port 9000
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/appName: "Mealie"
          hajimari.io/icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/refs/heads/main/svg/mealie.svg
        hosts:
          - host: &host "{{ .Release.Name }}.winterspring.ca"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: mealie
        globalMounts:
          - path: /app/data
      backups:
        type: nfs
        server: 192.168.100.5
        path: /storage/documents/mealie
        globalMounts:
          - path: /app/data/backups
