---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-nltk
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: mealie-nltk-bootstrap
