---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app suwayomi
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      suwayomi:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v1.1.1-r1673
            env:
              TZ: America/Toronto
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 512Mi
        pod:
          securityContext:
            runAsUser: 105000
            runAsGroup: 105000
            runAsNonRoot: true
            fsGroup: 105000
            fsGroupChangePolicy: "OnRootMismatch"
    service:
      app:
        controller: suwayomi
        ports:
          http:
            port: 4567
    ingress:
      app:
        enabled: true
        nameOverride: *app
        className: internal
        annotations:
          # external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/appName: "Suwayomi"
          hajimari.io/icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/svg/suwayomi.svg
        hosts:
          - host: &host '{{ .Release.Name }}.${SECRET_DOMAIN}'
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      media:
        type: nfs
        server: 192.168.100.5
        path: /storage/media/manga/tachidesk
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk
