---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Flux Kustomizations
  - ./tautulli/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./plex/ks.yaml
