---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Directories
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  SCRIPTS_DIR: "{{.ROOT_DIR}}/scripts"
  # Files
  AGE_FILE: "{{.ROOT_DIR}}/age.key"
  KUBECONFIG_FILE: "{{.ROOT_DIR}}/kubeconfig"

env:
  KUBECONFIG: "{{.KUBECONFIG_FILE}}"
  SOPS_AGE_KEY_FILE: "{{.AGE_FILE}}"

includes:
  bootstrap: .task/bootstrap
  create: .task/create
  flux: .task/flux
  k8s: .task/k8s
  # rook: .task/rook
  sops: .task/sops
  talos: .task/talos
  workstation: .task/workstation

tasks:

  default: task -l
