---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcsim-assets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gcsim-assets-secret
    template:
      engineVersion: v2
      data:
        SOURCE_HOST: "{{ .SOURCE_HOST }}"
        SOURCE_TYPE: "{{ .SOURCE_TYPE }}"
  dataFrom:
    - extract:
        key: gcsim-assets
