# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app gcsim-assets
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      gcsim-assets:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/genshinsim/assets-develop
              tag: v2.32.0 # {"$imagepolicy": "flux-system:gcsim-assets:tag"}
              pullPolicy: Always
            envFrom:
              - secretRef:
                  name: gcsim-assets-secret
            env:
              TZ: America/Toronto
              CACHE_DIR: /cache
              PORT: &port 3000
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: gcsim-assets
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        nameOverride: *app
        className: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host '{{ .Release.Name }}.${SECRET_DOMAIN}'
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      gcsim-assets-cache:
        existingClaim: gcsim-assets-cache
        globalMounts:
          - path: /cache
