---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcsim-assets-cache
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
