---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./postfinance.yaml
  - ./stakater.yaml
  - ./xenitab.yaml
  - ./piraeus.yaml
  - ./k8tz.yaml
  - ./external-secrets.yaml
  - ./backube.yaml
  - ./democratic-csi.yaml
  - ./prometheus-community.yaml
  - ./grafana.yaml
  - ./bitnami.yaml
  - ./hajimari-charts.yaml
  - ./cloudnative-pg.yaml
