---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volsync-test-nfs
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: volsync-test-nfs-bootstrap
