---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
  namespace: game-servers
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: minecraft
      version: 4.26.4
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 0 # if it fails stop trying prob config is wrong
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
  maxHistory: 3
  values:
    fullnameOverride: *app
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    serviceAnnotations:
      io.cilium/lb-ipam-ips: "192.168.100.46"
    # not using geyser for now - no bedrock clients
    # extraVolumes:
    #   - volumeMounts:
    #       - name: geyser-config-volume
    #         mountPath: /data/plugins/Geyser-Spigot/config.yml
    #         subPath: config.yml
    #     volumes:
    #       - name: geyser-config-volume
    #         configMap:
    #           name: geysermc-config
  valuesFrom:
    - kind: ConfigMap
      name: mincraft-values
    # - kind: Secret
    #   name: mincraft-secret
