---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  # namespace: services
  # labels:
  #   environment: production
  #   app: gitea
spec:
  interval: 15m
  chart:
    spec:
      chart: gitea
      version: 10.1.3
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    image:
      repository: gitea/gitea
      tag: 1.21.1
      pullPolicy: "Always"
      rootless: true

    replicaCount: 1

    containerSecurityContext:
      capabilities:
        add:
          - SYS_CHROOT

    ingress:
      enabled: true
      className: internal
      annotations:
        hajimari.io/icon: pajamas:gitea
      hosts:
        - host: &host "git.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    service:
      ssh:
        type: ClusterIP
        port: 22

    resources:
      limits:
        memory: 3Gi
      requests:
        cpu: 75m
        memory: 500Mi

    gitea:
      admin:
        username: 'gitea'
      config:
        APP_NAME: Gitea

        server:
          DISABLE_SSH: false
          SSH_PORT: 22
          SSH_LISTEN_PORT: 2222
          SSH_DOMAIN: "ssh.git.${SECRET_DOMAIN}"
          DOMAIN: "git.${SECRET_DOMAIN}"
          ROOT_URL: "https://git.${SECRET_DOMAIN}"
          ENABLE_GZIP: true
          LANDING_PAGE: login
          LFS_START_SERVER: true

        packages:
          enabled: true

        admin:
          DISABLE_REGULAR_ORG_CREATION: true
        ui:
          DEFAULT_THEME: arc-green
          THEMES: arc-green

        database:
          DB_TYPE: postgres
          NAME: giteadb
          SCHEMA: public
          HOST: postgres-rw.database.svc.cluster.local:5432
          SSL_MODE: disable
          MAX_OPEN_CONNS: 0
          MAX_IDLE_CONNS: 2
          CONN_MAX_LIFETIME: 0
          DB_RETRIES: 10

        webhook:
          ALLOWED_HOST_LIST: "*"

        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: false

        session:
          PROVIDER: db

        cache:
          ADAPTER: memory

        queue:
          TYPE: level

        cron:
          ENABLED: true

        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true

        storage:
          STORAGE_TYPE: minio
          MINIO_USE_SSL: false
          MINIO_INSECURE_SKIP_VERIFY: true
          MINIO_BUCKET: gitea
          MINIO_ENDPOINT: s3:http://minio.lan/

        actions:
          enabled: true

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      podAnnotations:
        secret.reloader.stakater.com/reload: gitea-secret

    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    redis-cluster:
      enabled: false

    persistence:
      enabled: true
      className: gitea
      storageClass: local-hostpath

  valuesFrom:
    - targetPath: gitea.admin.email
      kind: Secret
      name: gitea-secret
      valuesKey: adminEmail
    - targetPath: gitea.admin.password
      kind: Secret
      name: gitea-secret
      valuesKey: adminPassword
    # db
    - targetPath: gitea.config.database.PASSWD
      kind: Secret
      name: gitea-secret
      valuesKey: dbPassword
    - targetPath: gitea.config.database.USER
      kind: Secret
      name: gitea-secret
      valuesKey: dbUser
    # minio secrets
    - targetPath: gitea.config.storage.MINIO_ACCESS_KEY_ID
      kind: Secret
      name: gitea-secret
      valuesKey: AWS_ACCESS_KEY_ID
    - targetPath: gitea.config.storage.MINIO_SECRET_ACCESS_KEY
      kind: Secret
      name: gitea-secret
      valuesKey: AWS_SECRET_ACCESS_KEY
