kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: gitea
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gitea
  ingress:
  - from:
    # Allow ssh ingress
    - ipBlock:
        cidr: "0.0.0.0/0"
    ports:
    - protocol: TCP
      port: 22
      endPort: 22
  policyTypes:
    - Ingress
