---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: alertmanager
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      alertmanager:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: storage
              accessMode: ReadWriteOnce
              size: 50Mi
              storageClass: local-hostpath
              globalMounts:
                - path: /alertmanager

        containers:
          app:
            image:
              repository: quay.io/prometheus/alertmanager
              tag: v0.27.0
            ports:
              - name: http
                containerPort: 9093
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 11m
                memory: 50M
              limits:
                memory: 99M
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: alertmanager
        ports:
          http:
            port: 9093

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/appName: Alerts
          hajimari.io/icon: https://github.com/walkxcode/dashboard-icons/raw/main/svg/alertmanager.svg
        hosts:
          - host: &host alertmanager.winterspring.ca
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      # config:
      #   type: configMap
      #   name: alertmanager-configmap
      #   globalMounts:
      #     - path: /etc/alertmanager
      secrets:
        type: secret
        name: alertmanager-secret
        globalMounts:
          - path: /etc/alertmanager
