---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
  namespace: storage
spec:
  interval: 15m
  releaseName: zfs-nfs
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"

    csiDriver:
      # should be globally unique for a given cluster
      name: zfs-nfs.democratic-csi.main.cluster.local
      attachRequired: false

    controller:
      strategy: node

      driver:
        image:
          registry: ghcr.io/democratic-csi/democratic-csi
          tag: v1.9.3

      externalAttacher:
        image:
          registry: registry.k8s.io/sig-storage/csi-attacher
          tag: v4.10.0

      externalProvisioner:
        image:
          registry: registry.k8s.io/sig-storage/csi-provisioner
          tag: v5.3.0
        args:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=false
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1

      externalResizer:
        image:
          registry: registry.k8s.io/sig-storage/csi-resizer
          tag: v1.14.0

      externalSnapshotter:
        enabled: true
        image:
          registry: registry.k8s.io/sig-storage/csi-snapshotter
          tag: v8.2.1@sha256:5f4bb469fec51147ce157329dab598c758da1b018bad6dad26f0ff469326d769
        extraArgs:
          - --leader-election=false
          - --node-deployment=true

      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "node-role.kubernetes.io/control-plane"
                    operator: "Exists"

    node:
      driver:
        image:
          registry: ghcr.io/democratic-csi/democratic-csi
          tag: v1.9.3

      driverRegistrar:
        image:
          registry: registry.k8s.io/sig-storage/csi-node-driver-registrar
          tag: v2.15.0

      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists

    storageClasses:
      - name: zfs-nfs
        defaultClass: false
        reclaimPolicy: Retain
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
          # csi.storage.k8s.io/fstype: nfs
        mountOptions:
          - nfsvers=4.2
          - nconnect=8
          - hard
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    driver:
      existingConfigSecret: zfs-nfs-secret

    volumeSnapshotClasses:
      - name: zfs-nfs
        deletionPolicy: Delete
        parameters: {}
