---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app changedetection
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      changedetection:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: "0.45.17@sha256:20ac8284d3cb556c3fb13b03359e1040134f83d5cac4494ec7c008d83005db7d"
            env:
              TZ: America/Toronto
              PORT: &port 5000
              USE_X_SETTINGS: 1
              PLAYWRIGHT_DRIVER_URL: ws://localhost:3000/?stealth=1&--disable-web-security=true&--user-data-dir=~/browserless-cache-123
          browser:
            image:
              repository: docker.io/browserless/chrome
              tag: latest@sha256:57d19e414d9fe4ae9d2ab12ba768c97f38d51246c5b31af55a009205c136012f
            env:
              - {name: SCREEN_WIDTH, value: "1920"}
              - {name: SCREEN_HEIGHT, value: "1024"}
              - {name: SCREEN_DEPTH, value: "16"}
              - {name: ENABLE_DEBUGGER, value: "false"}
              - {name: PREBOOT_CHROME, value: "true"}
              - {name: CONNECTION_TIMEOUT, value: "300000"}
              - {name: MAX_CONCURRENT_SESSIONS, value: "10"}
              - {name: CHROME_REFRESH_TIME, value: "600000"}
              - {name: DEFAULT_BLOCK_ADS, value: "true"}
              - {name: DEFAULT_STEALTH, value: "true"}

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/appName: "Change Detection"
          hajimari.io/icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/changedetection-io.png?raw=true
        hosts:
          - host: &host '{{ .Release.Name }}.winterspring.ca'
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          changedetection:
            changedetection:
              - path: /datastore
