apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - config.ini
  name: obsidian-couchdb-configmap
  options:
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
    disableNameSuffixHash: true
kind: Kustomization
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
resources:
- couchdb-obsidian.yaml
