---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app sshwifty
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      sshwifty:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: niruix/sshwifty
              tag: latest
            env:
              TZ: America/Toronto
              SSHWIFTY_CONFIG: /config/sshwifty.json
            volumeMounts:
              - name: config
                mountPath: config
            resources:
              requests:
                cpu: 100m
                memory: 52M
              limits:
                memory: 256M
        volumes:
          - name: config
            configMap:
              name: sshwifty-configmap
              defaultMode: 0777
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8182
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "sshwifty"
          hajimari.io/icon: "remote-desktop"
          hajimari.io/targetBlank: "true"
        hosts:
          - host: &host "sshwifty.winterspring.ca"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
