---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sshwifty
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      sshwifty:
        containers:
          app:
            image:
              repository: niruix/sshwifty
              tag: latest
            env:
              TZ: "America/Toronto"
            resources:
              requests:
                cpu: 100m
                memory: 52M
              limits:
                memory: 256M
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8182
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "sshwifty"
          hajimari.io/info: "sshwifty remote access jumpbox"
          hajimari.io/icon: "remote-desktop"
          hajimari.io/targetBlank: "true"
        hosts:
          - host: &host sshwifty.winterspring.ca
            paths:
              - path: "/"
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
