---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go2rtc
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: go2rtc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go2rtc
    spec:
      containers:
        - name: app
          image: docker.io/alexxit/go2rtc:1.9.14@sha256:675c318b23c06fd862a61d262240c9a63436b4050d177ffc68a32710d9e05bae
          env:
            - name: TZ
              value: America/Toronto
          envFrom:
            - secretRef:
                name: go2rtc-secret
          ports:
            - name: api
              containerPort: 1984
              protocol: TCP
            - name: rtsp
              containerPort: 8554
              protocol: TCP
            - name: webrtc-tcp
              containerPort: 8555
              protocol: TCP
            - name: webrtc-udp
              containerPort: 8555
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: api
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: api
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: go2rtc-config
---
apiVersion: v1
kind: Service
metadata:
  name: go2rtc
  annotations:
    io.cilium/lb-ipam-ips: 192.168.100.61
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: go2rtc
  ports:
    - name: api
      port: 1984
      targetPort: api
      protocol: TCP
    - name: rtsp
      port: 8554
      targetPort: rtsp
      protocol: TCP
    - name: webrtc-tcp
      port: 8555
      targetPort: webrtc-tcp
      protocol: TCP
    - name: webrtc-udp
      port: 8555
      targetPort: webrtc-udp
      protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go2rtc
  annotations:
    hajimari.io/appName: go2rtc
    hajimari.io/icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/webrtc.svg
spec:
  ingressClassName: internal
  rules:
    - host: &host go2rtc.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go2rtc
                port:
                  name: api
  tls:
    - hosts:
        - *host
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: go2rtc-secret
    template:
      engineVersion: v2
      data:
        FRONTDOOR_RTSP_URL: "{{ .FRONTDOOR_RTSP_URL }}"
  dataFrom:
    - extract:
        key: go2rtc
