---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app kavita
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      kavita:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: kizaing/kavita
              tag: 0.7.8@sha256:48b3c2c07f90feb4641ddb791f96a1bf6e70a2b27da8c8b2ca0cc2c627b91d72
            env:
              TZ: America/Toronto
              CONFIG_PATH: /config
            resources:
              requests:
                cpu: 50m
                memory: 3Gi
              limits:
                memory: 8Gi
        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5000
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/appName: "Kavita"
          hajimari.io/icon: https://github.com/walkxcode/dashboard-icons/raw/main/svg/kavita.svg
        hosts:
          - host: &host '{{ .Release.Name }}.winterspring.ca'
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /kavita/config
      media:
        type: nfs
        server: 192.168.100.5
        path: /storage/media
        globalMounts:
          - path: /storage/media
