---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: silverbullet
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: silverbullet-secret
    template:
      engineVersion: v2
      data:
        SB_USER: "{{ .SB_USER }}"
  dataFrom:
    - extract:
        key: silverbullet
