---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app silverbullet
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 105000
        runAsGroup: 105000
        fsGroup: 105000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    controllers:
      silverbullet:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/zefhemel/silverbullet 
              tag: '0.10.1'
            env:
              TZ: America/Toronto
              PUID: 105000
              GUID: 105000
              SB_NAME: "srl notes"
            envFrom:
              - secretRef:
                  name: silverbullet-secret 
            resources:
              requests:
                cpu: 100m
                memory: 400Mi
              limits:
                cpu: 500m
                memory: 1Gi
    service:
      app:
        controller: silverbullet
        ports:
          http:
            port: 3000
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/appName: "Silverbullet"
          hajimari.io/icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/silverbullet.png
        hosts:
          - host: &host 'notes.${SECRET_DOMAIN}'
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      media:
        type: nfs
        server: 192.168.100.5
        path: /storage/documents/notes
        globalMounts:
          - path: /space
