---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rp-app
  namespace: flux-system
spec:
  interval: 30m
  path: ./
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: rp-kubernetes
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
      - kind: Secret
        name: cluster-secrets-user
        optional: true
