---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gitea
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: "./kubernetes/apps/services/gitea/app/"
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: external-secrets-stores
    - name: democratic-csi-local-path
    - name: volsync
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea-actions
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/services/gitea/action
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: gitea
    - name: external-secrets-stores
    - name: democratic-csi-local-path
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
