---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: runner-vol
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: act-runner
  name: act-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: act-runner
  strategy: {}
  template:
    metadata:
      labels:
        app: act-runner
    spec:
      securityContext:
        fsGroup: 2000
      restartPolicy: Always
      volumes:
        - name: runner-data
          persistentVolumeClaim:
            claimName: runner-vol
        - name: runner-cache
          emptyDir: {}
      containers:
        - name: runner
          image: vegardit/gitea-act-runner:dind-0.2.6
          imagePullPolicy: Always
          env:
            - name: GITEA_INSTANCE_URL
              value: http://gitea-http.services.svc.cluster.local:3000
            - name: GITEA_RUNNER_ACTION_CACHE_DIR
              value: /cache/actions
            - name: ACT_CACHE_SERVER_DIR
              value: /cache/server
            - name: GITEA_RUNNER_JOB_CONTAINER_NETWORK
              value: host
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea-actions-secret
                  key: token

          securityContext:
            privileged: true
            hostPID: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: runner-data
              mountPath: /data
            - name: runner-cache
              mountPath: /cache
