---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: act-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitea-actions-secret
    template:
      engineVersion: v2
      data:
        token: "{{ .RUNNER_TOKEN }}"
  dataFrom:
    - extract:
        key: gitea
