---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  # secrets should be for thanos which we're not using
  # - ./externalsecret.yaml
configMapGenerator:
  - name: kube-state-metrics-configmap
    files:
      - kube-state-metrics.yaml=./resources/kube-state-metrics.yaml
generatorOptions:
  disableNameSuffixHash: true
