---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openbooks
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      openbooks:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: docker.io/evanbuss/openbooks
              tag: 4.5.0@sha256:3f2e59a75b68950d57cfec5dc2b1b31d6c6b02706097c70b5438499b59fbdea2
            command: /app/openbooks
            env:
              TZ: America/Toronto
            args:
              - server
              - --dir
              - /ebooks
              - --port
              - "80"
              - --name
              - gimmeabreak
              - --useragent
              - "HexChat 2.9.1"
              - --searchbot
              - searchook
              - --persist
              - --server
              - "irc.irchighway.net:9999"

        pod:
          securityContext:
            runAsUser: 105000
            runAsGroup: 105000
            fsGroup: 105000
            fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: openbooks
        ports:
          http:
            port: 80

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: noto:books
        hosts:
          - host: &host "{{ .Release.Name }}.winterspring.ca"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      ebooks:
        type: nfs
        server: 192.168.100.5
        path: /storage/media/books/ebooks
