apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: gcsim-assets
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gcsim-assets
    namespace: home-kubernetes
  policy:
    semver:
      range: ">=2.0.0"
