apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: gcsim-updates
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: main
  update:
    # this is the path that flux searches for yaml to update it looks like
    path: ./kubernetes/apps/gcsim
    strategy: Setters
