---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app pgadmin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      pgadmin:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          volume-permissions:
            image:
              repository: dpage/pgadmin4
              tag: 9.8@sha256:d115bcd737940a6cfb61a54439d50de8b850e0782e2363102c9fa761f4022f49
            command: [/bin/chown, -R, 5050:5050, /var/lib/pgadmin]
            securityContext:
              runAsUser: 0
        containers:
          app:
            image:
              repository: dpage/pgadmin4
              tag: 9.8@sha256:d115bcd737940a6cfb61a54439d50de8b850e0782e2363102c9fa761f4022f49
            env:
              PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
              TZ: America/Toronto
            envFrom:
              - secretRef:
                  name: pgadmin-secret
            resources:
              requests:
                cpu: 15m
                memory: 164Mi
              limits:
                memory: 236Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/appName: "pgAdmin"
          hajimari.io/icon: https://github.com/walkxcode/dashboard-icons/raw/main/svg/pgadmin.svg
        hosts:
          - host: &host "pgadmin.winterspring.ca"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /var/lib/pgadmin
