---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mealie
  namespace: flux-system
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/services/mealie/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: external-secrets-stores
    - name: volsync
    - name: democratic-csi-local-path
  postBuild:
    substitute:
      APP: *app
      APP_UID: "105000"
      APP_GID: "105000"
      VOLSYNC_CAPACITY: 2Gi
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 3m
