apiVersion: batch/v1
kind: CronJob
metadata:
  name: rclone-sync 
  namespace: media
  labels:
    repo: home-kubernetes
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 45
  # ttlSecondsAfterFinished: 100
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 2
  jobTemplate:
    metadata:
      labels:
        cronjob: rclone-remote-sync 
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            cronjob: rclone-remote-sync
        spec:
          containers:
          - name: rclone-remote-sync 
            image: rclone/rclone 
            imagePullPolicy: IfNotPresent
            args:
            - sync
            - remotedata:/home/gimmeabreak/completed
            - /storage/media/data/completed 
            # - --dry-run 
            - --config=/config/rclone.conf 
            - --multi-thread-cutoff=50M 
            - --multi-thread-streams=4 
            - --filter-from=/filters/filter-list.txt 
            - --progress 
            - --partial-suffix=.partial
            - --log-level=INFO
            securityContext:
              runAsUser: 105000      
              runAsGroup: 105000     
            volumeMounts:
              - name: config
                mountPath: config
              - name: filters
                mountPath: filters
              - name: storage
                mountPath: /storage/media/data
          volumes:
            - name: config 
              secret:
                secretName: rclone-sync-secret
            - name: filters
              configMap:
                name: rclone-filter-configmap
            - name: storage
              nfs:
                server: 192.168.100.5
                path: /storage/media/data
          restartPolicy: Never
