---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Flux Kustomizations
  - ./gcsim-preview/ks.yaml
  - ./gcsim-rod/ks.yaml
  - ./gcsim-assets/ks.yaml
